INSERT INTO
    card (
        id,
        NAME,
        slug,
        description,
        TYPE,
        VALUE,
        deck_quantity,
        photo
    )
VALUES
    -- (1, 'Deal Breaker', 'deal_breaker', 'Steal a complete set of properties from any player.', 'action', 5, 2, NULL),
    -- (2, 'Debt Collector', 'debt_collector', 'Force any player to pay you 5M', 'action', 3, 3, NULL),
    -- (3, 'Double The Rent', 'double_rent', 'Needs to be played with a rent card.', 'action', 1, 2, NULL),
    -- (4, 'Forced Deal', 'forced_deal', 'Swap any property with another player.', 'action', 3, 3, NULL),
    -- (5, 'Hotel', 'hotel', 'Add onto any full set you own to add 4M to the rent value.', 'action', 4, 2, NULL),
    -- (6, 'House', 'house', 'Add onto any full set you own to add 3M to the rent value.', 'action', 3, 3, NULL),
    -- (7, 'It''s My Birthday', 'birthday', 'All players give you 2M as a gift.', 'action', 2, 3, NULL),
    -- (8, 'Just Say No', 'say_no', 'Use any time when an action card is played against you.', 'action', 4, 3, NULL),
    -- (9, 'Pass Go', 'pass_go', 'Draw 2 extra cards.', 'action', 1, 10, NULL),
    -- (10, 'Sly Deal', 'sly_deal', 'Steal a property from the player of your choice.', 'action', 3, 3, NULL);
    -- (11, 'Baltic Avenue', 'baltic_avenue', NULL, 'property', 1, 1, NULL),
    -- (12, 'Mediterranean Avenue', 'mediterranean_avenue', NULL, 'property', 1, 1, NULL),
    -- (13, 'Boardwalk', 'boardwalk', NULL, 'property', 4, 1, NULL),
    -- (14, 'Park Place', 'park_place', NULL, 'property', 4, 1, NULL),
    -- (15, 'North Carolina Avenue', 'nc_ave', NULL, 'property', 4, 1, NULL),
    -- (16, 'Pacific Avenue', 'pacific_ave', NULL, 'property', 4, 1, NULL),
    -- (17, 'Pennsylvania Avenue', 'pa_ave', NULL, 'property', 4, 1, NULL),
    -- (18, 'Connecticut Avenue', 'con_ave', NULL, 'property', 1, 1, NULL),
    -- (19, 'Oriental Avenue', 'oriental_ave', NULL, 'property', 1, 1, NULL),
    -- (20, 'Vermont Avenue', 'vermont_ave', NULL, 'property', 1, 1, NULL),
    -- (21, 'New York Avenue', 'ny_ave', NULL, 'property', 2, 1, NULL),
    -- (22, 'St. James Place', 'st_james_place', NULL, 'property', 2, 1, NULL),
    -- (23, 'Tennessee Avenue', 'ten_ave', NULL, 'property', 2, 1, NULL),
    -- (24, 'St. Charles Place', 'st_charles_place', NULL, 'property', 2, 1, NULL),
    -- (25, 'Virginia Avenue', 'va_ave', NULL, 'property', 2, 1, NULL),
    -- (26, 'States Avenue', 'states_ave', NULL, 'property', 2, 1, NULL),
    -- (27, 'Short Line', 'short_line', NULL, 'property', 2, 1, NULL),
    -- (28, 'B. & O. Railroad', 'bo_railroad', NULL, 'property', 2, 1, NULL),
    -- (29, 'Reading Railroad', 'reading_railroad', NULL, 'property', 2, 1, NULL),
    -- (30, 'Pennsylvania Railroad', 'pa_railroad', NULL, 'property', 2, 1, NULL),
    -- (31, 'Kentucky Avenue', 'ken_ave', NULL, 'property', 3, 1, NULL),
    -- (32, 'Indiana Avenue', 'ind_ave', NULL, 'property', 3, 1, NULL),
    -- (33, 'Illinois Avenue', 'il_ave', NULL, 'property', 3, 1, NULL),
    -- (34, 'Water Works', 'water_works', NULL, 'property', 2, 1, NULL),
    -- (35, 'Electric Company', 'electric_company', NULL, 'property', 2, 1, NULL),
    -- (36, 'Ventnor Avenue', 'vent_ave', NULL, 'property', 3, 1, NULL),
    -- (37, 'Marvin Gardens', 'marvin_gardens', NULL, 'property', 3, 1, NULL),
    -- (38, 'Atlantic Avenue', 'atlantic_ave', NULL, 'property', 3, 1, NULL),
    -- (39, 'Dark Blue and Green Wildcard', 'wc_db_g', NULL, 'wildcard', 4, 1, NULL),
    -- (40, 'Light Blue and Brown Wildcard', 'wc_lb_b', NULL, 'wildcard', 1, 1, NULL),
    -- (41, 'Multi-color Wildcard', 'wc_all', NULL, 'wildcard', 0, 2, NULL),
    -- (42, 'Pink and Orange Wildcard', 'wc_p_o', NULL, 'wildcard', 2, 2, NULL),
    -- (43, 'Green and Railroad Wildcard', 'wc_g_rr', NULL, 'wildcard', 4, 1, NULL),
    -- (44, 'Light Blue and Railroad Wildcard', 'wc_lb_rr', NULL, 'wildcard', 4, 1, NULL),
    -- (45, 'Utility and Railroad Wildcard', 'wc_u_rr', NULL, 'wildcard', 2, 1, NULL),
    -- (46, 'Red and Yellow Wildcard', 'wc_r_y', NULL, 'wildcard', 3, 2, NULL),
    -- (47, 'Wild Rent', 'rent_all', 'Force one player to pay you rent for properties you own in one of these colors.', 'rent', 3, 3, NULL),
    -- (48, 'Blue and Green Rent', 'rent_db_g', 'All players pay you rent for properties you own in one of these colors.', 'rent', 1, 2, NULL),
    -- (49, 'Brown and Light Blue Rent', 'rent_b_lb', 'All players pay you rent for properties you own in one of these colors.', 'rent', 1, 2, NULL),
    -- (50, 'Pink and Orange Rent', 'rent_p_o', 'All players pay you rent for properties you own in one of these colors.', 'rent', 1, 2, NULL),
    -- (51, 'Railroad and Utility Rent', 'rent_rr_u', 'All players pay you rent for properties you own in one of these colors.', 'rent', 1, 2, NULL),
    -- (52, 'Red and Yellow Rent', 'rent_r_y', 'All players pay you rent for properties you own in one of these colors.', 'rent', 1, 2, NULL),
    -- (53, '10M', '10m', NULL, 'money', 10, 1, NULL),
    -- (54, '1M', '1m', NULL, 'money', 1, 6, NULL),
    -- (55, '2M', '2m', NULL, 'money', 2, 5, NULL),
    -- (56, '3M', '3m', NULL, 'money', 3, 3, NULL),
    -- (57, '4M', '4m', NULL, 'money', 4, 3, NULL),
    -- (58, '5M', '5m', NULL, 'money', 5, 2, NULL),